services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - internal

networks:
  internal:
    external: true


#docker run -d `
#  --name kafka `
#  -p 9092:9092 `
#  -p 9093:9093 `
#  -p 9094:9094 `
#  --network internal `
#  -e KAFKA_NODE_ID=1 `
#  -e KAFKA_PROCESS_ROLES="broker,controller" `
#  -e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER `
#  -e KAFKA_CONTROLLER_QUORUM_VOTERS="1@localhost:9093" `
#  -e KAFKA_LISTENERS="PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,BROKER://0.0.0.0:9094" `
#  -e KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://localhost:9092,BROKER://localhost:9094" `
#  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT" `
#  -e KAFKA_INTER_BROKER_LISTENER_NAME=BROKER `
#  -e KAFKA_AUTO_CREATE_TOPICS_ENABLE="true" `
#  -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 `
#  -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 `
#  -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 `
#  -e KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0 `
#  -e KAFKA_NUM_PARTITIONS=1 `
#  apache/kafka:latest
#PS F:\AppStorage\patient-management> docker exec -it kafka env | findstr KAFKA
#KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
#KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
#KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
#KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
#KAFKA_NODE_ID=0
#KAFKA_PROCESS_ROLES=controller,broker