name: Build & Push Billing Service

on:
  push:
    paths:
      - 'billing-service/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/${{ secrets.PATIENT_DB_NAME }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.PATIENT_DB_USER }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.PATIENT_DB_PASSWORD }}
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/billing-service:latest ./billing-service

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/billing-service:latest
